services:
  - type: web
    name: flaskie
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: TRANSFORMERS_CACHE
        value: /tmp/transformers_cache
    memory: 1024